language: python
python:
  - "3.8"
before_install:
  - cd backend
install:
  - pip3 install -r requirements.txt
script:
  - python manage.py test blog/tests/unit
  - python manage.py test blog/tests/integration
  - python manage.py test blog/tests/e2e
